version: '3.9'
services:
    server:
        build: ./server
        ports:
            - '5000:5000'
    node:
        image: 'node:alpine'
        
    client:
        build: ./client
        ports:
            - '3000:3000'
    node:
        image: 'node:alpine'